### ISSUE TITLE
Permit the custom locale plugin to be used site-wide

### ISSUE THREAD

**Issue by asmecher** [langsci/customLocale#3]
See e.g.: https://forum.pkp.sfu.ca/t/using-custom-locale-plugin-in-web-site-level/49457/2

**Comment by mpbraendle** [comment]
That would be also a strong requirement from our side. The plugin fails on a multi-language, multi-journal installation. I get the following errors:

PHP Warning:  Declaration of CustomLocalePlugin::register($category, $path) should be compatible with LazyLoadPlugin::register($category, $path, $mainContextId = NULL) in /usr/local/service/www/ojs/plugins/generic/customLocale/CustomLocalePlugin.inc.php on line 198
PHP Warning:  Declaration of CustomLocalePlugin::getTemplatePath() should be compatible with Plugin::getTemplatePath($inCore = false) in /usr/local/service/www/ojs/plugins/generic/customLocale/CustomLocalePlugin.inc.php on line 198
PHP Fatal error:  Uncaught Error: Call to a member function getId() on null in /usr/local/service/www/ojs/plugins/generic/customLocale/CustomLocalePlugin.inc.php:32
Stack trace:
#0 /usr/local/service/www/ojs/lib/pkp/classes/plugins/PluginRegistry.inc.php(69): CustomLocalePlugin->register('generic', 'plugins/generic...', NULL)
#1 /usr/local/service/www/ojs/lib/pkp/classes/plugins/PluginRegistry.inc.php(140): PluginRegistry::register('generic', Object(CustomLocalePlugin), 'plugins/generic...', NULL)
#2 /usr/local/service/www/ojs/lib/pkp/classes/cliTool/CliTool.inc.php(65): PluginRegistry::loadCategory('generic')
#3 /usr/local/service/www/ojs/lib/pkp/classes/cliTool/UpgradeTool.inc.php(35): CommandLineTool->__construct(Array)
#4 /usr/local/service/www/ojs/tools/upgrade.php(29): UpgradeTool->__construct(Array)
#5 /usr/local/service/www/ojs/tools/upgrade.php(33): OJSUpgradeTool->__construct(Array)
#6 {main}
  thrown in /usr/local/service/www/ojs/plugins/generic/customLocale/CustomLocalePlugin.inc.php on line 32

**Comment by mpbraendle** [comment]
@CFanselow @Glottotopia anybody still around to cover this issue?

**Comment by hcoussy** [comment]
I @asmecher,
Have you plan to cover this issue in a next release ?
Thanks in advance for your answer.
Best regards.
Helene

**Comment by asmecher** [comment]
@hcoussy, we don't formally maintain this plugin; it's community owned. We may be able to put some effort into it occasionally, but don't have any timelines/milestones planned at the moment.
